<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Davids-MacBook-Pro.local" name="Scripts.android.LoginTests" tests="7" failures="0" timestamp="15 Sep 2015 17:41:03 GMT" time="28.541" errors="1">
  <testcase name="test1_4_1" time="3.216" classname="Scripts.android.LoginTests"/>
  <testcase name="test1_4_2" time="2.641" classname="Scripts.android.LoginTests"/>
  <testcase name="test1_3_2" time="2.885" classname="Scripts.android.LoginTests"/>
  <testcase name="test1_5_2" time="4.569" classname="Scripts.android.LoginTests">
    <error type="java.lang.AssertionError" message="Found Page Three">
      <![CDATA[java.lang.AssertionError: Found Page Three
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at lib.Library.evaluateTest(Library.java:680)
	at lib.Library.evaluateTest(Library.java:672)
	at Scripts.android.LoginTests.test1_5_2(LoginTests.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- test1_5_2 -->
  <testcase name="test1_2_1" time="7.022" classname="Scripts.android.LoginTests"/>
  <testcase name="test1_5_1" time="5.035" classname="Scripts.android.LoginTests"/>
  <testcase name="test1_3_1" time="3.173" classname="Scripts.android.LoginTests"/>
</testsuite> <!-- Scripts.android.LoginTests -->
